/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair(props) {
  const { nodes, materials } = useGLTF('chair.glb')
  const initialColor = { ...materials.ChairCloth2.color }
  const [color, setColor] = useState(initialColor)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.ChairCloth2}
        material-color={color}
        onPointerOver={() => setColor('#ff0000')}
        onPointerOut={() => setColor(initialColor)}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.KedeMat}
        material-color='#c3b3b4'
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.ChairClothMatPipes}
        material-color='#708ca2'
      />
    </group>
  )
}

useGLTF.preload('chair.glb')
